export const snackbarTitles = {
    gearAdded: { message: "Инвентарь добавлен", variant : "success" },
    gearAddFailed: { message: "Не удалось добавить инвентарь", variant : "error" },
    gearDeleted: { message: "Инвентарь успешно удалён", variant : "success" },
    gearDeleteFailed: { message: "Не удалось удалить инвентарь", variant : "error" },
    gearUpdated: { message: "Инвентарь редактирован", variant : "success" },
    gearUpdateFailed: { message: "Не удалось редактировать инвентарь", variant : "error" },
    trashAdded: { message: "Инвентарь успешно добавлен в корзину", variant : "success" },
    trashAddFailed: { message: "Не удалось добавить инвентарь в корзину", variant : "error" },
    statusChanged: { message: "Статус инвентаря изменён", variant : "success" },
    statusChangeFailed: { message: "Не удалось изменить статус инвентаря", variant : "error" },
    gearRecover: { message: "Инвентарь восстановлен успешно", variant : "success" },
    gearRecoverFailed: { message: "Не удалось восстановить инвентарь", variant : "error" },
    filterAdded: { message: "Фильтры добавлены успешно", variant : "success" },
    workerAdded: { message: "Сотрудник добавлен", variant : "success" },
    workerAddFailed: { message: "Не удалось добавить сотрудника", variant : "error" },
    workerUpdated: { message: "Сотрудник редактирован", variant : "success" },
    workerUpdateFailed: { message: "Не удалось редактировать сотрудника", variant : "error" },
    workerDeleted: { message: "Сотрудник успешно удалён", variant : "success" },
    workerDeleteFailed: { message: "Не удалось удалить сотрудника", variant : "error" },
  };
  